# Generated by Django 3.1.7 on 2021-04-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0004_project_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
